name: Build Simulator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install SDL2
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev
    - name: Build
      run: |
        mkdir -p simulator/build
        cd simulator/build
        cmake ..
        make
    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: simulator-linux
        path: simulator/build/simulator

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        mkdir simulator/build
        cd simulator/build
        cmake .. -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" -A x64
        cmake --build . --config Release
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: simulator-windows
        path: |
          simulator/build/Release/simulator.exe
          simulator/build/Release/*.dll

  build-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup emsdk
      uses: emscripten-core/setup-emsdk@v15
      with:
        version: 5.0.1
        emsdk-version: 5.0.5
        actions-cache-folder: 'emsdk-cache'
    - name: Verify
      run: emcc -v
    - name: Build Web
      run: |
        cd simulator
        mkdir build_web
        cd build_web
        emcmake cmake ..
        emmake make
    - name: Prepare Artifacts
      run: |
        mkdir -p simulator/dist
        cp simulator/build_web/simulator_web.html simulator/dist/index.html
        cp simulator/build_web/simulator_web.js simulator/dist/
        cp simulator/build_web/simulator_web.wasm simulator/dist/
    - name: Upload Web Artifact
      uses: actions/upload-artifact@v4
      with:
        name: simulator-web
        path: simulator/dist/
